import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { EdgeStoreProvider } from './libs/edgestore';
import Providers from "./providers";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <EdgeStoreProvider>
            <AppRouterCacheProvider>
        {children}
        </AppRouterCacheProvider>
        </EdgeStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
